In [1]:
# Set workspace
import sys
import os
workspace_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if workspace_root not in sys.path:
    sys.path.insert(0, workspace_root)

# Libraries

In [2]:
# Libraries
import pandas as pd
import numpy as np

In [3]:
# Other helpers

from helper_functions.utmb_api import (
    get_utmb_live_access_token,
    get_utmb_access_token,
    get_race_results,
    get_runner_results
)

# Get Data Examples

### UTMB API Authentication Token - Sign in with UTMB credentials
- Live Access Token - Get Race Data
- Access Token - Get Runner Data

In [6]:
# Get UTMB Sign in credentials (from environment variables)
from dotenv import load_dotenv
import os

load_dotenv()
utmb_website_login_username = os.getenv("utmb_website_login_username")
utmb_website_login_password = os.getenv("utmb_website_login_password")

In [9]:
# UTMB Live API Token
utmb_live_access_token = get_utmb_live_access_token(
    utmb_username=utmb_website_login_username, 
    utmb_password=utmb_website_login_password
)
print(f"UTMB Live API Access Token: {utmb_live_access_token[:10]}...")

UTMB Live API Access Token: eyJhbGciOi...

In [10]:
# UTMB API Token
utmb_access_token = get_utmb_access_token(
    utmb_username=utmb_website_login_username, 
    utmb_password=utmb_website_login_password
)
print(f"UTMB API Access Token: {utmb_access_token[:10]}...")

UTMB API Access Token: eyJhbGciOi...

### UTMB Race results

In [19]:
# Julian Alps Trail - 2025 - 80km
JAT80K_2025_results = get_race_results(
    race_id = "julianalps", 
    race_year = 2025, 
    course_id = "JAT80K", 
    access_token = utmb_live_access_token
)

display(JAT80K_2025_results)

Retrieving data for: julianalps ~ JAT80K ~ 2025

,race_id,race_name,race_category,race_start_time,runner_name,runner_url,runner_overall_index,runner_gender,runner_age,runner_country_code,...,runner_rank_category,runner_race_time,runner_diff_to_first_time,runner_final_status,runner_is_finisher,age,runner_race_time_hours,runner_diff_to_first_time_hours,race_start_time_hours,runner_final_status_map
0,JAT80K,LAKE BLED 80K,100k,2025-09-20T06:59:57.000Z,Karol SIOŁA,https://utmb.world/runner/3982818.karol.siola,789.0,H,24.0,PL,...,1,08:32:56,00:00:00,f,True,24,8.548889,0.000000,None,finisher
1,JAT80K,LAKE BLED 80K,100k,2025-09-20T06:59:57.000Z,Edoardo ROSSANO,https://utmb.world/runner/5062219.edoardo.rossano,816.0,H,32.0,IT,...,2,08:37:50,00:04:54,f,True,32,8.630556,0.081667,None,finisher
2,JAT80K,LAKE BLED 80K,100k,2025-09-20T06:59:57.000Z,Oliver SHAW,https://utmb.world/runner/6908095.oliver.shaw,NaN,H,27.0,GB,...,3,09:11:10,00:38:14,f,True,27,9.186111,0.637222,None,finisher
3,JAT80K,LAKE BLED 80K,100k,2025-09-20T06:59:57.000Z,Alex HAMLET,https://utmb.world/runner/4182477.alex.hamlet,748.0,H,34.0,GB,...,4,09:21:30,00:48:34,f,True,34,9.358333,0.809444,None,finisher
4,JAT80K,LAKE BLED 80K,100k,2025-09-20T06:59:57.000Z,Hannes VAN DE VREKEN,https://utmb.world/runner/2447457.hannes.vande...,576.0,H,37.0,BE,...,1,09:27:05,00:54:09,f,True,37,9.451389,0.902500,None,finisher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
672,JAT80K,LAKE BLED 80K,100k,2025-09-20T06:59:57.000Z,Andreea-Maria MESAROSI,https://utmb.world/runner/5718361.andreeamaria...,335.0,F,30.0,RO,...,44,02:04:34,None,a,False,30,2.076111,NaN,None,dnf
673,JAT80K,LAKE BLED 80K,100k,2025-09-20T06:59:57.000Z,Gašper KRAŠNJA,https://utmb.world/runner/5908353.gasper.krasnja,348.0,H,32.0,SI,...,183,02:14:54,None,a,False,32,2.248333,NaN,None,dnf
674,JAT80K,LAKE BLED 80K,100k,2025-09-20T06:59:57.000Z,Klára POSPÍCHALOVÁ,https://utmb.world/runner/6907195.klara.pospic...,332.0,F,28.0,CZ,...,45,02:51:48,None,a,False,28,2.863333,NaN,None,dnf
675,JAT80K,LAKE BLED 80K,100k,2025-09-20T06:59:57.000Z,Denis TRILLET,https://utmb.world/runner/2040419.denis.trillet,792.0,H,32.0,BE,...,184,03:44:12,None,a,False,32,3.736667,NaN,None,dnf
676,JAT80K,LAKE BLED 80K,100k,2025-09-20T06:59:57.000Z,Marina MILJKOVIC,https://utmb.world/runner/1583615.marina.miljk...,427.0,F,45.0,RS,...,21,00:00:00,None,c,False,45,0.000000,NaN,None,NaN

### UTMB Runner Statistics

In [22]:
# Tom Evans statistics
tom_evans_stats = get_runner_results(
    runner_id = "1410311.tom.evans", 
    access_token = utmb_access_token
)

display(tom_evans_stats)

,date,race_name,race_uri,piCategory,utmb_event_status,country,country_code,distance,elevation_gain,race_time,is_dnf,rank,rank_gender,total_finished,total_finished_gender,race_utmb_index,race_time_hours
0,2026-04-25,Three Peaks Race 2026,33016.threepeaksracethreepeaksrace.2026,50k,,United Kingdom,GB,39.00,1596,03:02:17,False,1.0,1.0,567,481,None,3.038056
1,2025-08-29,HOKA UTMB Mont-Blanc 2025 - UTMB,142.hokautmbmont-blancutmb.2025,100m,final,France,FR,174.20,9920,19:18:58,False,1.0,1.0,1665,1444,None,19.316111
2,2025-03-28,Tenerife Bluetrail by UTMB 2025 - TENERIFE BLU...,946.tenerifebluetrailbyutmbtenerifebluetrail11...,100m,event,Spain,ES,110.00,6250,12:32:20,False,1.0,1.0,325,293,None,12.538889
3,2025-01-25,Arc Of Attrition by UTMB 2025 - Arc 50,12555.arcofattritionbyutmbarc50.2025,100k,event,United Kingdom,GB,80.00,2300,06:54:40,False,1.0,1.0,348,290,None,6.911111
4,2024-08-30,HOKA UTMB Mont-Blanc 2024 - UTMB,142.hokautmbmont-blancutmb.2024,100m,final,France,FR,173.30,9525,None,True,NaN,NaN,1760,1555,None,NaN
5,2024-06-28,Lavaredo Ultra Trail by UTMB® 2024 - Lavaredo ...,178.lavaredoultratrailbyutmb-r-lavaredo120k.2024,100m,event,Italy,IT,122.30,5857,12:00:45,False,2.0,2.0,1240,1084,None,12.012500
6,2024-05-11,Transvulcania La Palma Island 2024 - ULTRAMARATÓN,708.transvulcanialapalmaislandultramaraton.2024,100k,,Spain,ES,73.06,4350,07:05:17,False,3.0,3.0,765,663,None,7.088056
7,2023-09-01,Dacia UTMB® Mont Blanc 2023 - UTMB,142.daciautmb-r-montblancutmb.2023,100m,final,France,FR,171.00,9963,None,True,NaN,NaN,1757,1569,None,NaN
8,2023-06-24,Western States Endurance Run 2023 - Western St...,327.westernstatesendurancerunwesternstates100-...,100m,event,United States of America,US,159.90,5610,14:40:22,False,1.0,1.0,328,260,None,14.672778
9,2023-05-13,Ultra-Trail Snowdonia by UTMB® 2023 - UTS 50K,21619.ultra-trailsnowdoniabyutmb-r-uts50k.2023,50k,event,United Kingdom,GB,55.00,3300,05:27:11,False,1.0,1.0,883,699,None,5.453056
10,2023-02-19,Black Canyon Ultras 2023 - 100K,3297.blackcanyonultras100k.2023,100k,,United States of America,US,99.90,1720,07:37:40,False,2.0,2.0,705,518,None,7.627778
11,2022-08-26,UTMB® Mont Blanc 2022 - UTMB®,142.utmb-r-montblancutmb-r-.2022,100m,final,France,FR,170.30,10050,20:34:35,False,3.0,3.0,1789,1651,None,20.576389
12,2022-06-04,Rab Scafell Sky Race 2022,27416.rabscafellskyracerabscafellskyrace.2022,50k,,United Kingdom,GB,40.00,2530,04:30:54,False,1.0,1.0,73,60,None,4.515000
13,2022-04-23,MIUT® - Madeira Island Ultra-Trail® 2022 - MIU...,1592.miut-r--madeiraislandultra-trail-r-miut85...,100k,,Portugal,PT,82.30,4780,08:46:35,False,1.0,1.0,339,263,None,8.776389
14,2022-03-05,Transgrancanaria 2022 - Advanced,1631.transgrancanariaadvanced.2022,50k,,Spain,ES,61.80,2430,05:10:39,False,1.0,1.0,594,471,None,5.177500
15,2020-02-08,Tarawera Ultramarathon 2020 - 102 km,895.taraweraultramarathon102km.2020,100k,,New Zealand,NZ,102.60,3790,08:03:29,False,1.0,1.0,506,347,None,8.058056
16,2019-06-29,Western States Endurance Run 2019,327.westernstatesendurancerunwesternstatesendu...,100m,,United States of America,US,160.70,5360,14:59:44,False,3.0,3.0,319,254,None,14.995556
17,2019-04-13,Lake Sonoma 50 2019,1341.lakesonoma50lakesonoma50.2019,100k,,United States of America,US,77.00,3080,06:16:28,False,3.0,3.0,280,200,None,6.274444
18,2019-01-19,Vibram Hong Kong 100 2019,906.vibramhongkong100vibramhongkong100.2019,100k,,"Hong Kong, China",HK,103.60,5300,None,True,NaN,NaN,1292,957,None,NaN
19,2018-08-31,UTMB® 2018 - CCC®,141.utmb-r-ccc-r-.2018,100k,,France,FR,100.10,6070,10:44:32,False,1.0,1.0,1622,1421,None,10.742222
20,2018-08-12,Meribel Trail 2018 - 23 km,6723.meribeltrail23km.2018,20k,,France,FR,23.60,1610,02:30:16,False,1.0,1.0,239,190,None,2.504444
21,2018-07-29,Montreux Trail Festival 2018 - MXSky,6777.montreuxtrailfestivalmxsky.2018,50k,,Switzerland,CH,37.90,2350,04:07:07,False,1.0,1.0,446,349,None,4.118611
22,2018-06-24,Ultramarathon Górski - 3 x Sniezka = 1 x Mont ...,14847.ultramarathongorski-3xsniezka-1xmontblan...,50k,,Poland,PL,36.60,2196,02:51:09,False,20.0,20.0,124,72,None,2.852500
23,2018-05-12,Penyagolosa Trails HG 2018 - IAUTWC,11003.penyagolosatrailshgiautwc.2018,100k,,Spain,ES,85.30,4900,08:49:35,False,3.0,3.0,263,159,None,8.826389
24,2018-04-07,Centurion South Downs Way 50 2018,1617.centurionsouthdownsway50centurionsouthdow...,50k,,United Kingdom,GB,78.50,1790,05:44:22,False,1.0,1.0,354,273,None,5.739444
25,2017-09-01,UTMB® 2017 - CCC®,141.utmb-r-ccc-r-.2017,100k,,France,FR,100.20,6150,10:57:44,False,4.0,4.0,1742,1484,None,10.962222
26,2017-07-15,Eiger Ultra-Trail® 2017 - E101,3970.eigerultra-trail-r-e101.2017,100k,,Switzerland,CH,98.10,7030,11:55:22,False,4.0,4.0,484,423,None,11.922778
27,2017-04-01,Le Marathon des Sables 2017,192.lemarathondessableslemarathondessables.2017,100m,,Morocco,MA,229.30,2880,19:49:33,False,3.0,3.0,1094,876,None,19.825833